server:
  port: 8080

spring:
  application:
    name: finwise-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/finwise_db}

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: 86400000 # 24 hours

ml-engine:
  base-url: ${ML_ENGINE_URL:http://localhost:8000}
